### ISSUE TITLE
[BUG] version_2.1.2项目YML配置文件启动报错 logback日志报错/各种报错 修复文档 by.zhoudeshui

### ISSUE THREAD

**Issue by RubyXun** [WeiYe-Jing/datax-web#690]
> 报错提示
> Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected:

## 完整修复配置
> admin模块配置文件
```YML
# 服务器配置-zhoudeshui
server:
  port: 9527

# Spring 配置
spring:
  # 数据源配置
  datasource:
    password: ${DB_PASSWORD:password}
    username: ${DB_USERNAME:username}
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_DATABASE:dataxweb}?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 数据库连接超时时间，默认300秒，即300000
      connection-timeout: 300000
      connection-test-query: SELECT 1
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      driver-class-name: com.mysql.cj.jdbc.Driver

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory

# 管理配置
management:
  health:
    mail:
      enabled: false
  server:
    servlet:
      context-path: /actuator

# MyBatis-Plus 配置
mybatis-plus:
  # mapper.xml 文件扫描路径
  mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml
  # 原注释保留：实体扫描，多个package用逗号或者分号分隔
  # 原注释保留：typeAliasesPackage: com.yibo.essyncclient.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      # 逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
      # 数据库类型
      db-type: mysql
    banner: false
  # MyBatis 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    type-handlers-package: com.wugui.datax.admin.core.handler

# 配置 MyBatis-Plus 打印 SQL 日志
logging:
  level:
    com.wugui.datax.admin.mapper: info
#  # windos路径
#    path: D:\\datax\\dataxweb\\applogs\\admin
#    path: ./data/applogs/admin

# DataX 作业配置
datax:
  job:
    accessToken:
    # i18n (default empty as chinese, "en" as english)
    i18n:
    # 触发器线程池最大大小
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    # 日志保留天数
    logretentiondays: 30

# 数据源 AES 加密配置
datasource:
  aes:
    key: AD42F6697B035B75
```

> executor模块配置文件
```YML
# 服务器配置-zhoudeshui
# Web 服务器端口配置
server:
  port: 9572

# 日志配置
logging:
  config: classpath:logback.xml
#  level:
#    # windows路径
#    path: D:\\datax\\dataxweb\\applogs\\executor\\jobhandler
#    path: ./data/applogs/executor/jobhandler


# DataX 作业相关配置
datax:
  job:
    admin:
      addresses: http://127.0.0.1:9527
    executor:
      appname: datax - executor
      ip:
      # 原注释保留：port: ${executor.port:9999}
      port: 9999
      # 作业日志路径
      # windows路径
      #logpath: D:\\datax\\dataxweb\\applogs\\executor\\jobhandler
      # 冗余配置
      logpath: ./data/applogs/executor/jobhandler
      # 作业日志保留天数
      logretentiondays: 30
    # 作业访问令牌
    accessToken:

  executor:
    # JSON 文件路径
    # windows路径
    #jsonpath: D:\\datax\\dataxweb\\temp\\executor\\json\\
    jsonpath: ./data/temp/executor/json

  # Python 脚本路径
  #windows路径
  #pypath: D:\\datax\\datax\\bin\\datax.py
  pypath: ../datax/bin/datax.py

# Python 解释器路径
python:
  path: /usr/bin/python

# 原注释保留：data:
# 原注释保留：  path: D:\\datax\\dataxweb
# 原注释保留：json:
# 原注释保留：  path: D:\\datax\\datax\\job
```
## 关键点
```YML
# executor
logging:
  config: classpath:logback.xml
# path: ${data.path}/applogs/executor/jobhandler
  path: ./data/applogs/executor/jobhandler
# executor原配置此处path与logback冲突故而造成错误 此处注释即可

# admin
logging:
  level:
    com.wugui.datax.admin.mapper: info
    path: ./data/applogs/admin
#  level:
#    com.wugui.datax.admin.mapper: error
#    path: ${data.path}/applogs/admin
# admin原配置path在level下无效配置 也算是误打误撞不会导致日志报错

```
**Which version of DataX Web:**
 -[2.1.2]
